    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: install pip-prereqs
      yum:
        name: epel-release
        state: latest
    
    - name: install pip
      yum:
        name: python-pip
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: install python docker
      pip:   
       name: docker
       version: latest

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add user centos to docker group
      user:
        name: centos
        groups: docker
        append: yes
      become: yes

    - name: pull blue image
      docker_image:
        name: runciblespoon/demo-blue
        source: pull

    - name: run blue image
      docker_container:
          name: blue-server
          image: runciblespoon/demo-blue
          published_ports: 9081:80


    - name: pull green image
      docker_image:
        name: runciblespoon/demo-green
        source: pull


    - name: run green image
      docker_container:
          name: green-server
          image: runciblespoon/demo-green
          published_ports: 9080:80
    
    - name: pull juiceshop image
      docker_image:
        name: bkimminich/juice-shop 
        source: pull
        
        
    - name: run juiceshop image
      docker_container:
          name: juice-server
          image: bkimminich/juice-shop
          published_ports: 3000:3000
