---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  vars_files:
    ../virtuals_pools.yml

  tasks:

  - name: ADD POOL MEMBERS
    bigip_pool_member:
      server: "{{private_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: "8443"
      state: "present"
      name: "{{hostvars[item[0]].inventory_hostname}}"
      host: "{{hostvars[item[0]].ansible_host}}"
      port: "80"
      pool: "{{item[1].pool_name}}"
      validate_certs: "no"
    with_nested:
      - "{{ groups['webservers'] }}"
      - "{{vips_pools}}"
