- name: Destroy lab instances in AWS
  hosts: localhost
  connection: local
  become: no
  gather_facts: no

  vars:
    ec2_wait: no
    teardown: true
    s3_state: absent
    state: absent

  tasks:
    - { include_role: {name: manage_ec2_instances}}

    - name: Remove workshop local files
      file:
        dest: "{{ playbook_dir }}/{{ ec2_name_prefix }}"
        state: absent
